title: Thom2503 Blog
description: >- # this means to ignore newlines until "baseurl:"
  Just a random blog with some of my thoughts.
twitter_username: thom2503
github_username:  Thom2503

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
